/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as qvBase from "./qv-base";
export type { qvBase };
import type * as qvSimple from "./qv-simple";
export type { qvSimple };
export type { BaseStrategy } from "./BaseStrategy";
