/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as alloProtocol from "./allo-protocol";
export { DoCMock__factory } from "./DoCMock__factory";
export { GenerateProfileId__factory } from "./GenerateProfileId__factory";
